

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (1, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (1, 30,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (1, 1, 1);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (2, 15,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (2, 25,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (2, 2, 2);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (3, 15,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (3, 3, 2);

